services:
  - type: web
    name: casiobot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /ping
    envVars:
      - key: TOKEN
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"